[package]
name = "gnirehtet"
version = "2.1.0"
authors = ["Romain Vimont <rvimont@genymobile.com>"]

[lib]
name = "relaylib"
path = "src/lib.rs"

[dependencies]
mio = "0.6"       # for async I/O
slab = "0.4"      # helper for mio Tokens
log = "0.3"       # for logs
chrono = "0.4"    # for formatting timestamp in logs
byteorder = "1.1" # for reading/writing binary
rand = "0.3"      # for random TCP sequence number
ctrlc = { version = "3.0", features = ["termination"] }     # for handling Ctrl+C

[profile.release]
lto = true     # link-time optimization

[replace]
# Current mio including this patch: https://github.com/carllerche/mio/pull/640
# to be removed when mio 0.6.11 is released
"mio:0.6.10" = { git = 'https://github.com/carllerche/mio', rev='5b9d20c4e01a63115ebdb6b87970fc9dd361a29b' }
